### ISSUE TITLE
Only Vedo alarm and not the HUB

### ISSUE THREAD

**Issue by reiantmulder** [gicamm/homeassistant-comelit#10]
HI there,

Great integration. I only have the VEDO alarm system and not the HUB for the other domotica.

Is there a way to switch of the HUB integration? and only use the integration of the alarm Vedo system,?

Many thanks, Reiant

**Comment by gicamm** [comment]
Hi Reiant,
basically, you could use only the VEDO integration
`# Comelit Hub/Vedo
comelit:
  vedo:
    host: VEDO IP ADDRESS
    port: 80
    password: VEDO PASSWORD
    scan_interval: 30`
However, I know there are issues using only the vedo integration.
I'll figure it out in the following days.

**Comment by reiantmulder** [comment]
Hi Gicamm,

Many thanks! When I use only the VEDO integration I get the following error in the logs:

Logger: homeassistant.setup
Source: custom_components/comelit/__init__.py:43 
Integration: Comelit Hub/Vedo ([documentation](https://github.com/gicamm/homeassistant-comelit)) 
First occurred: 17:37:03 (1 occurrences) 
Last logged: 17:37:03

Error during setup of component comelit
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/comelit/__init__.py", line 43, in setup
    hub_conf = conf["hub"]
KeyError: 'hub'

My configuration file looks like:

# Comelit Hub/Vedo
comelit:
   vedo:
     host: 192.168.1.230
     port: 80
     password: mypassword
     scan_interval: 30

**Comment by gicamm** [comment]
Got it. 
Thank you.

**Comment by gicamm** [comment]
Hi Reiant, 
please enjoy the fix.
Please let me know if you are experiencing issues.

**Comment by reiantmulder** [comment]
Hi Gicam,

Again many thanks.
I updated to your last version.

When I insert the configuration in the configuration file home assistant keeps on rebooting:

Verbinding verbroken. Opnieuw aan het verbinden…

Dutch for: connection terminated. Restore the connection (of home assistant).

If I comment out the configuration it doesn't go in the reboot cycle:

# Comelit Hub/Vedo
# comelit:
#   vedo:
#     host: 192.168.1.230
#     port: 80
#     password: 147258
#     scan_interval: 30

Any idea? or help? much appreciated.

Thanks, Reiant.

**Comment by gicamm** [comment]
Please attach your configuration file. Please hide your sensitive data before.
Tnx

**Comment by reiantmulder** [comment]
-------
# Comelit Hub/Vedo
comelit:
  vedo:
    host: 192.168.1.230
    port: 80
    password: bypassword
    scan_interval: 30
-----

**Comment by reiantmulder** [comment]
[configuration.txt](https://github.com/gicamm/homeassistant-comelit/files/9851486/configuration.txt)

**Comment by gicamm** [comment]
Can you attach the log?
Thx

**Comment by reiantmulder** [comment]
Hi Gicamm,

In the logs it doensn't give me errors (when I have the configuration active, but I reboots immediately, so the logs are empty from this perspective). When I comment out the configuration it doesn't reboot.

Regards, Reiant

**Comment by reiantmulder** [comment]
Hi Gicamm,

Any thoughts on improving this? Many thanks and kind regards,

Reiant.

**Comment by gicamm** [comment]
Hi Reiant,
Unfortunately, I do not understand what is happening.
I cannot reproduce it; without logs, it isn't easy to figure it out.

G
