### ISSUE TITLE
Blinds has wrong buttons

### ISSUE THREAD

**Issue by dotPIX** [gicamm/homeassistant-comelit#35]
Hi gicamm,
thank you so much for your addon. I've been struggling with blinds lately.
HA reports them with wrong command buttons so I can't open or close them.
When a blind is closed just the close button is available.
I reviewed your code and it seems correct, I'm scratching my head around this issue for a few days now...

![blinds](https://user-images.githubusercontent.com/3974826/223187154-7ef81abd-46e0-41a7-bc31-b47632ff22a3.png)

**Comment by dotPIX** [comment]
Hi gicamm, I've just tested your latest commit.
Now it works as expected.
Thank you.

**Comment by gicamm** [comment]
Thanks for the feedback
