### ISSUE TITLE
Comelit VEDO 34 support

### ISSUE THREAD

**Issue by optiluca** [gicamm/homeassistant-comelit#51]
Hi.  I've never been able to get my VEDO alarm system to work with this.  I can't work out if I'm just misunderstanding something, or if my VEDO system is not actually supported.

I have a VEDO 34 unit.  I can turn the alarm on/off from the Comelit APP, as well as from an (awful) SimpleHome mini touchscreen or an (even more awful) keypad + LCD display.  The only "password" I'm aware of is the PIN I have to insert to disarm the system.

My Comelit Hub (the one that all the MQTT chatter happens with) is at 192.168.1.231.  I also have 2 other mystery Comelit devices on my network (.230 and .232).

Based on your code, I gather that the Vedo side of things is not on MQTT.   It would also seem to be hosted at a different IP.

I ran a traffic analyser on my phone as I used the Comelit app to arm / disarm the alarm, but looking at the traffic I see nothing that resembles what the code of this integration seems to do.

The evidence is that my Vedo system is hosted at 192.168.1.230, and that communication is happening on port 10012.  The communication is all very binary-looking, however.  The only intelligible strings are the status messages I receive when the alarm has been armed or disarmed.  I see nothing resembling the login strings that the integration constructs.

In any case, I tried running the integration with vedo host = 192.168.1.230, vedo port = 10012, pass but it immediately fails at login:
`requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.1.230', port=10012): Read timed out` 

Am I missing something?

Grazie,

Luca

**Comment by gicamm** [comment]
Hi Luca,
The Vedo unit requires the Vedo IP.
https://pro.comelitgroup.com/it-it/prodotto/vedoip
It is a small expansion attached to the vedo board. It has a LAN port. The integration reaches the Vedo device. It does not require the comelit HUB.
You need to configure the HA with something like this:
```
comelit:
  vedo:
  host: X.X.X.X
  port: 80
  password: VEDO_PIN
```
The VEDO_PIN is the passcode you use for turning the alarm on/off. You could create a Vedo user for that scope.

The vedo IP exposes a web page http://X.X.X.X:80
![image](https://github.com/gicamm/homeassistant-comelit/assets/1204975/21a48fca-9940-464e-a57d-19e777fdd4ef)

**Comment by optiluca** [comment]
My other comelit devices (. 230 and. 232) don't seem to expose anything on port 80.

I'll have a better look at it over the weekend.

Thanks!

**Comment by optiluca** [comment]
Got it working - .230 was indeed a Vedo IP card, but it had been configured on a non-standard port.  I found the correct port and it's working now!
