### ISSUE TITLE
Comelit integration unresponsive

### ISSUE THREAD

**Issue by Nivlac7** [gicamm/homeassistant-comelit#54]
Hello,

I upgraded home assistant Core to 2023.11.2 for your comelit integration, thanks for making this available.

I have been using the homebridge version of Comelit to expose my lights switches and curtains in homekit and that’s working very well (https://github.com/madchicken/homebridge-comelit-sb).

I am now willing to move everything to home assistant and therefore tried your integration. Unfortunately this make the whole system quite unresponsive:
- up to 10 sec for a light to react
- around 15-20 sec to get the status update in HA and often « unavailable »
- The whole HA seems to be affected as everything else become extremely slow as well.

I am using a raspberry pi 3B with only HA straight on ethernet cable (as I do for homebridge btw) and everything was discovered without any problem. I only have this and a couple other integrations (very light HA)

I have a comelit Serial Bridge.

I had to desactivate it for now… anything I may be missing to have it working properly?

thanks for your work and assistance!

**Comment by gicamm** [comment]
Hi,
Nobody has encountered this problem yet.
Are you experiencing a spike in CPU usage?
However, can you attach your configuration?

**Comment by Nivlac7** [comment]
Using a raspberry pi 3 with 1G memory, that may indeed be the issue. I just ordered a rpi4 8 Gb, so I will migrate my home assistant to it and come back to you in a few days.

**Comment by gicamm** [comment]
The integration does not support the serial bridge.
See the wiki https://github.com/gicamm/homeassistant-comelit/wiki for more details.

Can you explain a bit about 'conflicting elements' in the doc?
Perhaps something is not clear.

**Comment by Nivlac7** [comment]
My bad, I am using simplehome from the Core integration which turns out not to be your integration :/
So confusion is not coming from your side at least :D

**Comment by gicamm** [comment]
No problem :)
