### ISSUE TITLE
numerical password causes login error

### ISSUE THREAD

**Issue by Just-inc-ace** [gicamm/homeassistant-comelit#68]
When a numercial password with leading zeros is used in the config.yaml leading zeros are dropped.
So 000000 is interpreted as 0.

Solution:
Modify
`        self.hub_password = hub_password`
in
`        self.hub_password = str(hub_password)`
in hub.py

**Comment by gicamm** [comment]
Hi, if you prefer, you can do the change yourself and submit a pull request.

**Comment by gicamm** [comment]
I agree, I'll change the wiki to better cover this case.
Anyway, you should use a better password :D.

**Comment by gicamm** [comment]
Close this one. Just updated the wiki and the README.md page.
Thanks
