### ISSUE TITLE
Error During Setup of Component Comelit

### ISSUE THREAD

**Issue by Marcoletto** [gicamm/homeassistant-comelit#69]
Hello @gicamm ,
here you are the new error appeared today.

I updated comelit integration 1 hour ago (due to a modification of cover.py)
then, I updated HA about 20mins ago.

After that you can see the results below.

Please, could you fix it?
At the moment the integration doesn' t work

Do you need other infos?

Registratore: homeassistant.setup
Fonte: setup.py:398
Prima occorrenza: 21:59:44 (1 occorrenze)
Ultima registrazione: 21:59:44

Error during setup of component comelit
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 398, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/comelit/__init__.py", line 38, in setup
    conf = config[DOMAIN]
           ~~~~~~^^^^^^^^
KeyError: 'comelit'



Also, these wanings are important to check:

Registratore: homeassistant.components.alarm_control_panel
Fonte: helpers/deprecation.py:206
Integrazione: Pannello di controllo degli allarmi (documentazione, problemi)
Prima occorrenza: 22:19:03 (6 occorrenze)
Ultima registrazione: 22:19:03

SUPPORT_ALARM_ARM_HOME was used from comelit, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_HOME instead, please report it to the author of the 'comelit' custom integration
SUPPORT_ALARM_ARM_AWAY was used from comelit, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_AWAY instead, please report it to the author of the 'comelit' custom integration
SUPPORT_ALARM_ARM_NIGHT was used from comelit, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_NIGHT instead, please report it to the author of the 'comelit' custom integration



Registratore: homeassistant.components.binary_sensor
Fonte: helpers/deprecation.py:206
Integrazione: Sensore binario (documentazione, problemi)
Prima occorrenza: 22:19:03 (4 occorrenze)
Ultima registrazione: 22:19:03

DEVICE_CLASS_PRESENCE was used from comelit, this is a deprecated constant which will be removed in HA Core 2025.1. Use BinarySensorDeviceClass.PRESENCE instead, please report it to the author of the 'comelit' custom integration
DEVICE_CLASS_MOTION was used from comelit, this is a deprecated constant which will be removed in HA Core 2025.1. Use BinarySensorDeviceClass.MOTION instead, please report it to the author of the 'comelit' custom integration




Registratore: homeassistant.const
Fonte: helpers/deprecation.py:206
Prima occorrenza: 22:19:03 (6 occorrenze)
Ultima registrazione: 22:19:03

TEMP_CELSIUS was used from comelit, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'comelit' custom integration
POWER_WATT was used from comelit, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead, please report it to the author of the 'comelit' custom integration
DEVICE_CLASS_HUMIDITY was used from comelit, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.HUMIDITY instead, please report it to the author of the 'comelit' custom integration
DEVICE_CLASS_TEMPERATURE was used from comelit, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.TEMPERATURE instead, please report it to the author of the 'comelit' custom integration
DEVICE_CLASS_POWER was used from comelit, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.POWER instead, please report it to the author of the 'comelit' custom integration





Registratore: homeassistant.components.climate.const
Fonte: helpers/deprecation.py:206
Integrazione: Climatizzatore (documentazione, problemi)
Prima occorrenza: 22:19:03 (1 occorrenze)
Ultima registrazione: 22:19:03

SUPPORT_TARGET_TEMPERATURE was used from comelit, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please report it to the author of the 'comelit' custom integration

**Comment by gicamm** [comment]
It seems you have a bad configuration. It seems you have some additional parameters in the configuration.yml file.
Can you attach your Comelit configuration?

**Comment by Marcoletto** [comment]
But is strange; I don't touch anythings; only update Intrgration with last version and same for HA.

Here you are the configuration.yaml (but it is only for the panel)
Where can I find other parameters?

`
alarm_control_panel:
  - platform: template
    panels:
      safe_alarm_panel:
        value_template: "{{ states('alarm_control_panel.esterno') }}"
#        value_template: "{{ (is_state('alarm_control_panel.esterno','armed_away')) and (is_state('alarm_control_panel.interno_garage','armed_away')) }}"
        name: Home Alarm
#        code_arm_required: true
        arm_away:
          service: alarm_control_panel.alarm_arm_away
          target:
            entity_id:
              - alarm_control_panel.esterno
              - alarm_control_panel.interno_garage
          data:
            code: !secret Vedo_PSW

        disarm:
          - condition: template
            value_template: !secret Vedo_PSW_Template
          - service: alarm_control_panel.alarm_disarm
            target:
              entity_id: 
              - alarm_control_panel.esterno
              - alarm_control_panel.interno_garage
            data:
              code: !secret Vedo_PSW

`

**Comment by gicamm** [comment]
I'm asking for the Comelit configuration, so the section with the 'hub' and/or 'vedo'
```
comelit:
  hub:
.........
  vedo:
.........
```

**Comment by Marcoletto** [comment]
I'm sorry... the integration wasn' t work before.
I use the official integration and seems that it works
