### ISSUE TITLE
[custom_components.comelit.vedo] Error getting data! cookie expired

### ISSUE THREAD

**Issue by Gmatarrubia** [gicamm/homeassistant-comelit#83]
Hello,

First of all congrats on your incredible work!

I would like to know what to do when the VEDO device stops working and the logs show the following message.

`[custom_components.comelit.vedo] Error getting data! cookie expired`

Thanks in advance.

**Comment by gicamm** [comment]
Hi Gonzalo,
this error usually happens when the token expires, but the integration should get a new token anyway. Didn't happen?

**Comment by Gmatarrubia** [comment]
No, it did not. I tried to reboot HA without success. Should I remove and add back the Comelit integration?
I wonder if there is a way to manually remove the old cookie so the integration must get a new one.

**Comment by gicamm** [comment]
Typically, when the cookie expires, the integration will automatically log in and get the new cookie.

![image](https://github.com/gicamm/homeassistant-comelit/assets/1204975/9d2f7d3a-3f93-42b2-a2ef-ffd20b347c4f)

However, you can remove/update/reinstall the integration by clicking on the 3 dot on the right.
Anyway, can you put your configuration here?

**Comment by gicamm** [comment]
close due to inactivity
