### ISSUE TITLE
Vedo 34 firmware compatibility

### ISSUE THREAD

**Issue by alexvit73** [gicamm/homeassistant-comelit#89]
Hi gicamm,
I try to find information about firmware update of Vedo34.
I have installed firmware 2.7.5 and I would like to update it to the last firmware 2.15.x: hardware_boot_version is 0x11. Is possible to update this hw with the last firmware? I know that is out of topic but I could found anywhere else information. For vedoip, vedo8i8o, vedoprox any restriction to update to the last version?
Thanks in advance 
Alex

**Comment by gicamm** [comment]
Hi Alex,
We have an interesting discussion here.
[https://github.com/gicamm/homeassistant-comelit/pull/81](https://github.com/gicamm/homeassistant-comelit/pull/81)
Looking at the output, the messages are the same and have not changed access to the versions. However, I cannot guarantee this.
We still have some work to do.
Basically, the integration reaches the video IP, so it is the most important element in the chain.
It would be interesting to get more feedback, and we could eventually work on compatibility issues.
Do you think you can help?

**Comment by alexvit73** [comment]
I can confirm that the integration work perfectly with last version of IP interface 2.8.1 and 15.1 of the central unit. Great job!
