### ISSUE TITLE
Unable to connect Vedo

### ISSUE THREAD

**Issue by mrdotsign** [gicamm/homeassistant-comelit#90]
For some reason, I cannot connect to my Vedo system. When restarting HA I'm getting the following message:

<img width="688" alt="Screenshot 2024-08-08 at 13 23 09" src="https://github.com/user-attachments/assets/51be1d7d-75b1-489d-add6-02060d8c4b33">

as you can see I already tried to increase the timeout to 30s (just to be sure)

current configuration:

   vedo:
    host: 192.168.1.230
    port: 80 (also tried other ports 10012, 10012)
    password: ***
    scan_interval: 30
    
  Local network parameters config in Comelit app:
  
  
![IMG_3968](https://github.com/user-attachments/assets/8bf6de49-1bf1-47f6-95ad-c87f51e54497)

the integration with my hub is working fine.

**Comment by gicamm** [comment]
Hi,
the port should be 80.
The integration uses the [VEDOIP](https://pro.comelitgroup.com/product/vedoip) which exposes a web application on port 80. It is accessible via a browser.
Either way, you'll get a timeout, so it's something to check in the connection.

**Comment by fvanlaere** [comment]
Hi mrdotsign, I have a feeling that we have the same installer (omnicron?) since my ip also ends with .230. For me they configured it to run on port 6082. Perhaps that one works for you as well.

**Comment by mrdotsign** [comment]
Hi @fvanlaere, yes my installer is indead omnicron! And you're right, I can indeed access the Vedo control panel on port 6082! How did you find this out? Also any idea where I should find the password? Since the password I found in their documentation (to configure the device within the Comelit app) doesn't seem to work (the alarm sets off after rebooting HA).

**Comment by fvanlaere** [comment]
@mrdotsign I think I asked them during the installation, but you can also find that port in the forward port of your internet provider (at least for me it's the first one of the 4 configured ports).
The password I use is my own password to arm/disarm the alarm from the physical keypad. It was configured during installation.

**Comment by fvanlaere** [comment]
@mrdotsign You're welcome! FYI: my alarm also goes off when I tried the "official" comelit integration by Home Assistant (https://www.home-assistant.io/integrations/comelit/). The password I use that works for this integration would set off the alarm in the "official" integration every time Home Assistant rebooted (for intrusion protection or something - if I remember well).
