### ISSUE TITLE
Climate controller 

### ISSUE THREAD

**Issue by mario-rossi78** [gicamm/homeassistant-comelit#92]
In my system I have a temperature/humidity sensor in each room. With Comelit app I can set the temperature for hot and cold mode independently. I can also manage the dehumidifier. The Comelit integration seem to have some limits and let you manage the hot modality only.

![WhatsApp Image 2024-08-12 at 15 08 08](https://github.com/user-attachments/assets/866c2267-527a-437c-81c5-78e2883d3c78)
![WhatsApp Image 2024-08-12 at 15 08 09 (1)](https://github.com/user-attachments/assets/a4cc0f27-07bb-4129-94f4-c099c8b41d28)
![WhatsApp Image 2024-08-12 at 15 08 09](https://github.com/user-attachments/assets/9e568967-b132-45b9-9889-551c0e2dc35d)
![WhatsApp Image 2024-08-12 at 15 08 10 (1)](https://github.com/user-attachments/assets/771424e4-9d2e-456d-be65-b84d6104c919)
![WhatsApp Image 2024-08-12 at 15 08 10](https://github.com/user-attachments/assets/c7fd9ed4-c168-4af3-b0b6-45059859d740)
![WhatsApp Image 2024-08-12 at 15 14 48](https://github.com/user-attachments/assets/0828c582-1eab-4dc8-a63f-965dddfc5022)

**Comment by gicamm** [comment]
We already have a request for that. We can continue there.
[https://github.com/gicamm/homeassistant-comelit/issues/88](https://github.com/gicamm/homeassistant-comelit/issues/88)

**Comment by gicamm** [comment]
We already have a request for that. We can continue there.
[https://github.com/gicamm/homeassistant-comelit/issues/88](https://github.com/gicamm/homeassistant-comelit/issues/88)
